FROM python:3.11.2-slim

RUN pip install poetry

COPY pyproject.toml poetry.lock /tests/

WORKDIR /tests

RUN poetry config virtualenvs.create false \
    && poetry install --no-interaction --no-ansi || echo "Poetry install failed"

COPY . .

CMD ["pytest"]